# Generated by Django 5.0.4 on 2024-04-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedLab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
